CREATE DATABASE Airport

USE Airport

CREATE TABLE Passengers
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FullName VARCHAR(100) UNIQUE NOT NULL,
Email VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Pilots
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(30) UNIQUE NOT NULL,
LastName VARCHAR(30) UNIQUE NOT NULL,
Age TINYINT NOT NULL,
Rating FLOAT,

CONSTRAINT CHK_Pilots_Age
CHECK (Age BETWEEN 21 AND 62),

CONSTRAINT CHK_Pilots_Rating
CHECK (Rating BETWEEN 0.0 AND 10.0),
)

CREATE TABLE AircraftTypes
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
TypeName VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE Aircraft
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Manufacturer VARCHAR(25) NOT NULL,
Model VARCHAR(30) NOT NULL,
[Year] INT NOT NULL,
FlightHours INT,
Condition CHAR(1) NOT NULL,
TypeId INT NOT NULL

CONSTRAINT FK_Aircraft_AircraftTypes
FOREIGN KEY (TypeId) REFERENCES AircraftTypes(Id)
)

CREATE TABLE PilotsAircraft
(
AircraftId INT NOT NULL,
PilotId INT NOT NULL

CONSTRAINT PK_PilotsAircraft
PRIMARY KEY (AircraftId, PilotId),

CONSTRAINT FK_PilotsAircraft_Aircraft
FOREIGN KEY (AircraftId) REFERENCES Aircraft(Id),

CONSTRAINT FK_PilotsAircraft_Pilots
FOREIGN KEY (PilotId) REFERENCES Pilots(Id)
)

CREATE TABLE Airports
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AirportName VARCHAR(70) UNIQUE NOT NULL,
Country VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE FlightDestinations
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AirportId INT NOT NULL,
[Start] DATETIME NOT NULL,
AircraftId INT NOT NULL,
PassengerId INT NOT NULL,
TicketPrice DECIMAL(18, 2) DEFAULT(15) NOT NULL

CONSTRAINT FK_FlightDestinations_Airports
FOREIGN KEY (AirportId) REFERENCES Airports(Id),

CONSTRAINT FK_FlightDestinations_Aircraft
FOREIGN KEY (AircraftId) REFERENCES Aircraft(Id),

CONSTRAINT FK_FlightDestinations_Passengers
FOREIGN KEY (PassengerId) REFERENCES Passengers(Id),
)
