CREATE DATABASE [Service]

USE [Service]

CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Username VARCHAR(30) UNIQUE NOT NULL,
[Password] VARCHAR(50) NOT NULL,
[Name] VARCHAR(50),
Birthdate DATETIME2,
Age INT,
Email VARCHAR(50) NOT NULL,

CONSTRAINT CHK_Users_Age
CHECK (Age BETWEEN 14 AND 110)
)

CREATE TABLE Departments
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Employees
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(25),
LastName VARCHAR(25),
Birthdate DATETIME2,
Age INT,
DepartmentId INT,

CONSTRAINT CHK_Employees_Age
CHECK (Age BETWEEN 18 AND 110),

CONSTRAINT FK_Employees_Departments
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)
)

CREATE TABLE Categories
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL

CONSTRAINT FK_Categories_Departments
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)
)

CREATE TABLE [Status]
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Label] VARCHAR(20) NOT NULL
)

CREATE TABLE Reports
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
CategoryId INT NOT NULL,
StatusId INT NOT NULL,
OpenDate DATETIME2 NOT NULL,
CloseDate DATETIME2,
[Description] VARCHAR(200) NOT NULL,
UserId INT NOT NULL,
EmployeeId INT

CONSTRAINT FK_Reports_Categories
FOREIGN KEY (CategoryId) REFERENCES Categories(Id),

CONSTRAINT FK_Reports_Status
FOREIGN KEY (StatusId) REFERENCES [Status](Id),

CONSTRAINT FK_Reports_Users
FOREIGN KEY (UserId) REFERENCES Users(Id),

CONSTRAINT FK_Reports_Employees
FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
)