CREATE DATABASE CigarShop

USE CigarShop

CREATE TABLE Sizes
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Length] INT NOT NULL,
RingRange DECIMAL(3, 2) NOT NULL,

CONSTRAINT CHK_Sizes_Length
CHECK ([Length] BETWEEN 10 AND 25),

CONSTRAINT CHK_Sizes_RingRange
CHECK (RingRange BETWEEN 1.50 AND 7.50)
) 

CREATE TABLE Tastes
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
TasteType VARCHAR(20) NOT NULL,
TasteStrength VARCHAR(15) NOT NULL,
ImageURL NVARCHAR(100) NOT NULL
)

CREATE TABLE Brands
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
BrandName VARCHAR(30) UNIQUE NOT NULL,
BrandDescription VARCHAR(MAX)
)

CREATE TABLE Cigars
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
CigarName VARCHAR(80) NOT NULL,
BrandId INT NOT NULL,
TastId INT NOT NULL,
SizeId INT NOT NULL,
PriceForSingleCigar MONEY NOT NULL,
ImageURL NVARCHAR(100) NOT NULL

CONSTRAINT FK_Cigars_Brands
FOREIGN KEY (BrandId) REFERENCES Brands(Id),

CONSTRAINT FK_Cigars_Tastes
FOREIGN KEY (TastId) REFERENCES Tastes(Id),

CONSTRAINT FK_Cigars_Sizes
FOREIGN KEY (SizeId) REFERENCES Sizes(Id)
)

CREATE TABLE Addresses
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Town VARCHAR(30) NOT NULL,
Country NVARCHAR(30) NOT NULL,
Streat NVARCHAR(100) NOT NULL,
ZIP VARCHAR(20) NOT NULL
)

CREATE TABLE Clients
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
Email NVARCHAR(50) NOT NULL,
AddressId INT NOT NULL

CONSTRAINT FK_Clients_Addresses
FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)

CREATE TABLE ClientsCigars
(
ClientId INT NOT NULL,
CigarId INT NOT NULL

CONSTRAINT PK_ClientsCigars
PRIMARY KEY (ClientId, CigarId),

CONSTRAINT FK_ClientsCigars_Clients
FOREIGN KEY (ClientId) REFERENCES Clients(Id),

CONSTRAINT FK_ClientsCigars_Cigars
FOREIGN KEY (CigarId) REFERENCES Cigars(Id)
)